FROM node:latest
WORKDIR /app
COPY . /app
ARG YANDEX_WEBMASTER_KEY
ENV YANDEX_WEBMASTER_KEY $YANDEX_WEBMASTER_KEY
ARG YANDEX_METRIKA_KEY
ENV YANDEX_METRIKA_KEY $YANDEX_METRIKA_KEY
RUN npm i
RUN npm run build
CMD npm run start
